FROM node:latest

ENV CONSUMER_KEY=CONSUMER_KEY
ENV CONSUMER_SECRET=CONSUMER_SECRET
ENV ACCESS_TOKEN=ACCESS_TOKEN
ENV ACCESS_TOKEN_SECRET=ACCESS_TOKEN_SECRET

ENV HOME=/home/app
COPY package.json $HOME/vvarbot/
WORKDIR $HOME/vvarbot
ENV NODE_PATH=/home/node_modules
VOLUME $NODE_PATH

RUN npm install pm2 -g

CMD ["pm2-runtime", "./src/index.js"]
